apiVersion: v1
kind: Service
metadata:
  name: resume-service
  namespace: dev  # Ensure the namespace matches your environment
spec:
  selector:
    app: resume-app  # Must match the label in the deployment
  ports:
    - protocol: TCP
      port: 80         # External service port
      targetPort: 80   # Port exposed by the container
  type: LoadBalancer   # Exposes it externally
